---
chezmoi_age_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66343462313062316434646132636130643261323330356165643430313037626137346537333437
          3161373134386165303236383938626461303337656466320a363231363439626666633734646464
          62376136343566636535643730636430623832326538333138313635363064653130346136656236
          3666366234653039360a306132376534626162306434643463613130656666623337636431666162
          30343437636565333434383239383266303530643766343134303330396238343035623532323664
          66323166323366356265343433326335346433646234643664373063643766383234666266373638
          33393438623038336562623532343463643138633266336265336638383765323636646461356662
          37333962323362336133363834653338626333616433373430353539383461313461646336643966
          38336633633739383839643936656533303431343935386266643734393031316461383934613130
          31623637656462373666313836346233656534613733656665363732643662366630303939323836
          30613531356635626133363436363137373062343238346539623934333933666562336330396637
          61386563346433386264336262373834373865323664663435646533316166363962363161333536
          34663231663237616430396466393234636564303436616331633562643331366665
